name: Java CI with Gradle for testng

on:
 push:
  branches: [testng]
 pull_request:
  branches: [testng]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test

# Команда `chmod +x gradlew` делает файл gradlew исполняемым в linux. 
# Команда `./gradlew test` собирает ваш проект и запускает тесты.
